Microservice Design Pattern
-----------------------------
1.Aggregator
2.API Gateway
3.Chained or Chain of Responsibility
4.Asynchronous messaging
5.Database Design pattern
6.Event Sourcing
7.Branch Pattern
8.Command Query Responsibility Segregation(CQRS)
9.Circuit Breaker
10.Decomposition

Microservice Tools:-
-----------------------
Tools for Api Management and Testing
1.Postman
2.API Fortress

Tool forMessage:-
1.Apache kafka
2.RabbitMq


ToolsKit
1.Fabric 8
2.Sceneca

Architecture Framework
1.Goa
2.Kong
Tools for Orchestration

1.Kubernetes
2.istio

Tools for monitoring
1.Promethues
2.LogStash

ServerLess tools
1.Aws Lambda
2.Claudia


